//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkMift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Books()
        {
            this.OrderBook = new HashSet<OrderBook>();
        }
    
        public int id { get; set; }
        public string title { get; set; }
        public Nullable<int> idAuthor { get; set; }
        public Nullable<int> idGenre { get; set; }
        public Nullable<System.DateTime> datePublic { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> countPages { get; set; }
        public string Annotation { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual Genre Genre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBook { get; set; }
    }
}
