//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CursWorkMift
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderBook = new HashSet<OrderBook>();
        }
    
        public int id { get; set; }
        public Nullable<int> idUser { get; set; }
        public Nullable<int> idStatus { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<int> count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderBook> OrderBook { get; set; }
        public virtual Status Status { get; set; }
        public virtual Users Users { get; set; }
    }
}
